#!/bin/bash

sed -e 's/{{LOGROTATE_MODE}}/'"$LOGROTATE_MODE"'/' \
    -e 's/{{LOGROTATE_ROTATE}}/'"$LOGROTATE_ROTATE"'/' \
    /app/logrotate.tmpl > /etc/logrotate.d/docker
chmod 0644 /etc/logrotate.d/docker
exec /usr/local/bin/go-cron "$GOCRON_SCHEDULER" /etc/cron.daily/logrotate

